//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wSQL.Language.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wSQL.Language.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare page, list, descriptionNodes, descriptions
        ///
        ///set page = load(&quot;https://www.google.com/search?q=something+to+search&amp;cad=cbv&amp;sei=drQPVuWtDoS7acCjptgG&quot;)
        ///print page
        ///set list = find(page, &quot;//div[class=&apos;srg&apos;]/div[class=&apos;g pb&apos;]&quot;)
        ///set descriptionNodes = flatten(map(list, it =&gt; find(it, &quot;div[class=&apos;st&apos;]&quot;)))
        ///set descriptions = map(descriptionNodes, it =&gt; it.InnerText)
        ///print descriptions
        ///.
        /// </summary>
        internal static string Sample1 {
            get {
                return ResourceManager.GetString("Sample1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare page, list, descriptionNodes, descriptions
        ///
        ///set page = load(&quot;https://www.google.com/search?q=something+to+search&amp;cad=cbv&amp;sei=drQPVuWtDoS7acCjptgG&quot;)
        ///print page
        ///set list = find(page, &quot;//div[class=&apos;srg&apos;]/div[class=&apos;g pb&apos;]&quot;)
        ///set descriptionNodes = flatten(map(list, it =&gt; find(it, &quot;div[class=&apos;st&apos;]&quot;)))
        ///set descriptions = map(descriptionNodes, it =&gt; it.InnerText)
        ///print descriptions
        ///.
        /// </summary>
        internal static string Sample2 {
            get {
                return ResourceManager.GetString("Sample2", resourceCulture);
            }
        }
    }
}
